import Head from "next/head";
import dynamic from "next/dynamic";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DynamicSlides />
      </main>
    </>
  );
}

const DynamicSlides = dynamic(
  () => import("../components/Slides").then(mod => mod.Slides),
  {
    loading: () => (
      <div
        style={{
          position: "fixed",
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
        }}
      >
        Loading&nbsp;&hellip;
      </div>
    ),
    ssr: false,
  },
);
